[package]
name = "gitice"
version = "1.0.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>", "Amogh Lele <amolele@gmail.com>"]
edition = "2018"
description = "Freeze your local git repositories for easy restoration"
repository = "https://github.com/msfjarvis/gitice"
homepage = "https://github.com/msfjarvis/gitice"
license = "MIT/Apache-2.0"
keywords = ["git", "snapshot", "backup", "restore"]
readme = "README.md"
include = ["src/**/*", "LICENSE-*", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.4", features = [ "color", "deprecated", "derive" ] }
git2 = { version = "0.15.0", default-features = false, features = ["vendored-libgit2", "vendored-openssl"] }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_derive = "1.0.145"
toml = "0.5.9"
walkdir = "2.3.2"

[badges]
maintenance = { status = "actively-developed" }
