[package]
name = "gitice"
version = "1.0.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>", "Amogh Lele <amolele@gmail.com>"]
edition = "2018"
description = "Freeze your local git repositories for easy restoration"
repository = "https://github.com/msfjarvis/gitice"
homepage = "https://github.com/msfjarvis/gitice"
license = "MIT/Apache-2.0"
keywords = ["git", "snapshot", "backup", "restore"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.2"
git2 = "0.13.11"
serde = {version = "1.0.116", default-features = false, features = ["derive"] }
serde_derive = "1.0.116"
toml = "0.5.7"
walkdir = "2.3.1"

[badges]
maintenance = { status = "actively-developed" }
