on:
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md
 
name: Check Rust code
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-rust-project.yml@main
